In [247]:
import  numpy as np

In [248]:
#Generate a random 10 by 10 matrix with random integers chosen from [1,1000]
matrix1 = np.random.randint(1,1000,size=(10,10))
matrix1


array([[372, 762, 570, 981, 791, 844, 867, 805,   7, 533],
       [944, 726, 613, 750, 638, 187, 868, 969,  16, 353],
       [829, 938, 909, 529, 784, 353, 201, 903, 314, 498],
       [859, 985, 396, 831, 178, 826,  74, 889, 225, 424],
       [218, 893, 665, 679, 836, 883, 778,  50,  47, 708],
       [906, 466, 741, 149, 892,  54, 923, 553, 658, 769],
       [480, 704, 795, 588, 902, 929, 338, 715, 406, 790],
       [900, 147, 936,  74, 935, 734, 500, 782, 128, 154],
       [102, 215, 166, 468, 664, 798, 630, 355, 776, 422],
       [400, 869, 103, 725, 587, 101, 408, 439, 412, 478]])

In [258]:
#Suppose the following dictionary saves the information about the data submission with respect to the original 10 by 10 matrix: 
#{‘Bob’:[0,3,7],’Alice’:[2,4,8],’Caro’:[1,9],’Dave’:[5,6]}. For example, Bob submitted the 1st, 4th, and 8th rows 
#and Caro submitted the 2nd and 10th rows. Calculate the following items:
list1 = matrix1.tolist()
dict1= {}
dict1= {'Bob' :list1[0]+list1[3]+list1[7], 
        'Alice' : list1[2]+list1[4]+list1[8] , 
        'Caro' : list1[1]+list1[9] , 
        'Dave' : list1[5]+list1[6] 
                       
                       }




In [250]:
#a.	The mean of data submitted by Bob and Caro together
res1 = dict1['Bob']+dict1['Caro']
mean= sum(res1)/len(res1)
mean
    


561.9

In [251]:
#b.	The column-wise mean of data submitted by Alice
res2= dict1['Alice']
alice = np.array(res2).reshape(3,10)
alice
mean1= np.mean(alice, axis =0)
mean1

array([383.        , 682.        , 580.        , 558.66666667,
       761.33333333, 678.        , 536.33333333, 436.        ,
       379.        , 542.66666667])

In [252]:
#c Data from Dave where they are greater than 500, if any
dave = np.array(dict1['Dave'])
ans= np.array(dave[dave>500])
ans


array([906, 741, 892, 923, 553, 658, 769, 704, 795, 588, 902, 929, 715,
       790])

In [253]:
#d.	The row-wise standard deviation of data submitted by Caro and Dave
caro = np.array(dict1['Caro']).reshape(2,10)
dave = np.array(dict1['Dave']).reshape(2,10)
x= np.concatenate((caro,dave),axis=0)

std= np.std(x, axis =1)
std

array([306.35508809, 227.75636105, 292.48673474, 194.05517257])

In [254]:
#e.	Data from Bob where they are greater than their element-wise counterpart from Alice, if any
bob = np.array(dict1['Bob']).reshape(3,10)
alice = np.array(dict1['Alice']).reshape(3,10)
bob[alice>bob] =0
bob
    


array([[  0,   0,   0, 981, 791, 844, 867,   0,   0, 533],
       [859, 985,   0, 831,   0,   0,   0, 889, 225,   0],
       [900,   0, 936,   0, 935,   0,   0, 782,   0,   0]])

In [255]:
#Define a function called get_even, which takes a numpy 2d-array as input and returns all the values inside
#that are even numbers.
# (i). for random numbers
def get_even(A):
    assert(type(A) == np.ndarray and A.ndim == 2)
    return A[A%2 == 0]         
X = np.random.randint(1,100,size=(3,4))
get_even(X)


array([90, 12, 96, 88, 98, 50])

In [256]:
# (ii). for the input specified in file (Sample output file)
def get_even(A):
    assert(type(A) == np.ndarray and A.ndim == 2)
    return A[A%2 == 0]
                             
x=[[1,4,8],[1,9,6]]
X=np.array(x)
get_even(X)


array([4, 8, 6])

In [259]:
import math
def pad(A, edge=1):
    assert(type(A) == np.ndarray and A.ndim == 2)
     
    zero_matrix = np.zeros([A.shape[0]+2*edge, A.shape[1]+2*edge])
    zero_matrix_rows = zero_matrix.shape[0]
    given_matrix_rows = A.shape[0]
    x = (zero_matrix_rows // 2) - (given_matrix_rows // 2)
    y = math.ceil((zero_matrix_rows / 2)) + (given_matrix_rows // 2)
    A = zero_matrix[x:y, x:y]
    return zero_matrix

twobytwo = np.random.randint(1,100,size=(2,2))
print(pad(twobytwo))

three_dimension = np.random.randint(1,100,size=(3,3))
pad(three_dimension,2)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])